# This is a build environment for Quantori SCIP product for CentOS 7.
#
# How to build:  docker build --rm --tag build/r/amazon:2 --file Dockerfile.centos7 ./
# How to build bundle: docker run -it -v $(pwd):/build --name build-R build/r/centos:7
#
# Arguments:
#  - workspace is a path to build directory inside containers;

FROM registry.hub.docker.com/library/centos:7

ARG packages=rpm-build
ARG workspace=/build

LABEL maintainer="Quantori DevOps <scip-ops@quantori.com>"
LABEL product="scip"
LABEL vendor="Quantori"
LABEL com.quantori.scip.build-env.version="1.0.0"

ENV RPM_TOPDIR ${workspace}/rpmbuild
ENV RPM_BUILD_DEPS ${packages}
ENV SHELL /bin/bash
ENV TERM xterm

RUN yum install epel-release -y && \
    yum install -y curl make which && \
    yum install -y \
        autoconf \
        automake \
        bzip2-devel \
        gcc-c++ \
        less \
        rpm-build \
        xz-devel \
        ${RPM_BUILD_DEPS//:/ } && \
    mkdir -p ${RPM_TOPDIR}/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} && \
    chmod o+rwx,+t ${RPM_TOPDIR}/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

WORKDIR $workspace

CMD ["/bin/bash"]
